sylius_resource:
    resources:
        bitbag_sylius_product_bundle.product_bundle:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusProductBundlePlugin\Entity\ProductBundle
                interface: BitBag\SyliusProductBundlePlugin\Entity\ProductBundleInterface
                form: BitBag\SyliusProductBundlePlugin\Form\Type\ProductBundleType
                repository: BitBag\SyliusProductBundlePlugin\Repository\ProductBundleRepository
